import '../models/menu_item.dart';

class MenuData {
  static List<MenuItem> allItems = [
    // BURGERS
    MenuItem(
      id: 'b1',
      name: 'Regular Burger',
      emoji: '🍔',
      price: 170,
      oldPrice: 200,
      category: 'Burgers',
    ),
    MenuItem(
      id: 'b2',
      name: 'Shami & Anda Burger',
      emoji: '🍔',
      price: 220,
      oldPrice: 300,
      category: 'Burgers',
    ),
    MenuItem(
      id: 'b3',
      name: 'Boti Burger',
      emoji: '🍔',
      price: 350,
      oldPrice: 400,
      category: 'Burgers',
    ),
    MenuItem(
      id: 'b4',
      name: 'Zinger Burger',
      emoji: '🍔',
      price: 380,
      oldPrice: 450,
      category: 'Burgers',
      tag: 'Spicy',
    ),
    MenuItem(
      id: 'b5',
      name: 'Chicken Burger',
      emoji: '🍔',
      price: 300,
      oldPrice: 400,
      category: 'Burgers',
    ),
    MenuItem(
      id: 'b6',
      name: 'Petty Burger',
      emoji: '🍔',
      price: 250,
      oldPrice: 300,
      category: 'Burgers',
    ),
    MenuItem(
      id: 'b7',
      name: 'Double Egg Lapeta Burger',
      emoji: '🍔',
      price: 200,
      oldPrice: 250,
      category: 'Burgers',
    ),
    MenuItem(
      id: 'b8',
      name: 'Mighty Burger',
      emoji: '🍔',
      price: 500,
      category: 'Burgers',
      tag: 'Special',
    ),

    // SHAWARMA
    MenuItem(
      id: 's1',
      name: 'Regular Shawarma',
      emoji: '🌯',
      price: 280,
      oldPrice: 350,
      category: 'Shawarma',
    ),
    MenuItem(
      id: 's2',
      name: 'Zinger Shawarma',
      emoji: '🌯',
      price: 380,
      oldPrice: 450,
      category: 'Shawarma',
      tag: 'Spicy',
    ),
    MenuItem(
      id: 's3',
      name: 'Kabab Shawarma',
      emoji: '🌯',
      price: 250,
      oldPrice: 300,
      category: 'Shawarma',
    ),
    MenuItem(
      id: 's4',
      name: 'Platter Shawarma',
      emoji: '🌯',
      price: 600,
      oldPrice: 700,
      category: 'Shawarma',
      tag: 'Best Seller',
    ),
    MenuItem(
      id: 's5',
      name: 'Special Shawarma',
      emoji: '🌯',
      price: 350,
      oldPrice: 400,
      category: 'Shawarma',
      tag: 'Special',
    ),

    // WRAPS
    MenuItem(
      id: 'w1',
      name: 'Chicken Paratha',
      emoji: '🥙',
      price: 370,
      oldPrice: 400,
      category: 'Wraps',
    ),
    MenuItem(
      id: 'w2',
      name: 'Zinger Paratha',
      emoji: '🥙',
      price: 400,
      oldPrice: 450,
      category: 'Wraps',
      tag: 'Spicy',
    ),
    MenuItem(
      id: 'w3',
      name: 'Kabab Paratha',
      emoji: '🥙',
      price: 300,
      oldPrice: 350,
      category: 'Wraps',
    ),
    MenuItem(
      id: 'w4',
      name: 'Arabic Wrap',
      emoji: '🥙',
      price: 550,
      oldPrice: 600,
      category: 'Wraps',
      tag: 'Special',
    ),
    MenuItem(
      id: 'w5',
      name: 'Shappata Roll',
      emoji: '🥙',
      price: 600,
      category: 'Wraps',
      tag: 'Loaded',
    ),

    // SANDWICHES
    MenuItem(
      id: 'sw1',
      name: 'Chicken Sandwich',
      emoji: '🥪',
      price: 350,
      oldPrice: 400,
      category: 'Sandwiches',
    ),
    MenuItem(
      id: 'sw2',
      name: 'Club Sandwich',
      emoji: '🥪',
      price: 400,
      oldPrice: 500,
      category: 'Sandwiches',
      tag: 'Classic',
    ),

    // FRIES & SIDES
    MenuItem(
      id: 'f1',
      name: 'Regular Fries',
      emoji: '🍟',
      price: 200,
      category: 'Fries',
    ),
    MenuItem(
      id: 'f2',
      name: 'Half Loaded Fries',
      emoji: '🍟',
      price: 350,
      category: 'Fries',
    ),
    MenuItem(
      id: 'f3',
      name: 'Full Loaded Fries',
      emoji: '🍟',
      price: 600,
      category: 'Fries',
      tag: 'Cheesy',
    ),
    MenuItem(
      id: 'f4',
      name: '5 Nuggets',
      emoji: '🍗',
      price: 250,
      category: 'Fries',
    ),
    MenuItem(
      id: 'f5',
      name: '5 Zinger Wings',
      emoji: '🍗',
      price: 700,
      category: 'Fries',
      tag: 'Spicy',
    ),
    MenuItem(
      id: 'f6',
      name: 'Mayo Dip',
      emoji: '🧂',
      price: 50,
      category: 'Fries',
    ),
    MenuItem(
      id: 'f7',
      name: 'BBQ Dip',
      emoji: '🍯',
      price: 80,
      category: 'Fries',
    ),
    MenuItem(
      id: 'f8',
      name: 'Chilli Garlic Dip',
      emoji: '🌶️',
      price: 50,
      category: 'Fries',
    ),
    MenuItem(
      id: 'f9',
      name: 'Extra Bread',
      emoji: '🍞',
      price: 50,
      category: 'Fries',
    ),
    MenuItem(
      id: 'f10',
      name: 'Cheese Slice',
      emoji: '🧀',
      price: 50,
      category: 'Fries',
    ),

    // DRINKS
    MenuItem(
      id: 'd1',
      name: '300ml Drink',
      emoji: '🥤',
      price: 80,
      category: 'Drinks',
    ),
    MenuItem(
      id: 'd2',
      name: 'Half Litre Drink',
      emoji: '🥤',
      price: 120,
      category: 'Drinks',
    ),
    MenuItem(
      id: 'd3',
      name: '1 Litre Drink',
      emoji: '🥤',
      price: 150,
      category: 'Drinks',
    ),
    MenuItem(
      id: 'd4',
      name: '1.5 Litre Drink',
      emoji: '🥤',
      price: 200,
      category: 'Drinks',
    ),
  ];

  static List<MenuItem> getByCategory(String category) {
    if (category == 'All') return allItems;
    return allItems.where((item) => item.category == category).toList();
  }

  static List<String> get categories => [
    'All',
    'Burgers',
    'Shawarma',
    'Wraps',
    'Sandwiches',
    'Fries',
    'Drinks',
  ];

  static List<Map<String, dynamic>> deals = [
    {
      'num': 1,
      'name': 'Deal 1',
      'desc': '1 Zinger Burger + Mayo Dip + 300ml Drink',
      'price': 480,
      'emoji': '🍔',
    },
    {
      'num': 2,
      'name': 'Deal 2',
      'desc': '5 Shami & Anda Burger + 1.5 Ltr Drink',
      'price': 1000,
      'emoji': '🍔',
    },
    {
      'num': 3,
      'name': 'Deal 3',
      'desc': '2 Shawarma + 1 Zinger Burger + 1.5 Ltr Drink',
      'price': 1100,
      'emoji': '🌯',
    },
    {
      'num': 4,
      'name': 'Deal 4',
      'desc': '4 Chicken Burger + 1.5 Ltr Drink',
      'price': 1200,
      'emoji': '🍔',
    },
    {
      'num': 5,
      'name': 'Deal 5',
      'desc': '4 Kabab Shawarma + 1.5 Ltr Drink',
      'price': 1150,
      'emoji': '🌯',
    },
    {
      'num': 6,
      'name': 'Deal 6',
      'desc': '2 Zinger Burger + 1 Petty Burger + 1 Ltr Drink',
      'price': 1100,
      'emoji': '🍔',
    },
    {
      'num': 7,
      'name': 'Deal 7',
      'desc': '2 Zinger + 2 Chicken Burger + 1 Petty Burger + 1.5 Ltr Drink',
      'price': 1750,
      'emoji': '🔥',
    },
    {
      'num': 8,
      'name': 'Deal 8',
      'desc': '5 Regular Shawarma + 1.5 Ltr Drink',
      'price': 1550,
      'emoji': '🌯',
    },
    {
      'num': 9,
      'name': 'Deal 9',
      'desc': 'Arabic Wrap + 5 Nuggets + Half Ltr Drink',
      'price': 1100,
      'emoji': '🥙',
    },
    {
      'num': 10,
      'name': 'Deal 10',
      'desc': '1 Petty Burger + 1 Regular Drink',
      'price': 300,
      'emoji': '🍔',
    },
  ];
}
